#! /usr/bin/env bash
echo 'Removing targets from dist directory...'
find ~/Dropbox/Tech/Projects/Pancake/dist -type f -name '*.js' -exec rm "{}" +
find ~/Dropbox/Tech/Projects/Pancake/dist -type f -name '*.map' -exec rm "{}" +
find ~/Dropbox/Tech/Projects/Pancake/dist -type f -name '*.json' -exec rm "{}" +
echo 'Copying over configuration files...'
cp -f src/syrup/api/apiconfig_priv.json dist/syrup/api/apiconfig_priv.json
cp -f src/valet/api/apiconfig.json dist/valet/api/apiconfig.json
cp -f src/valet/api/valet_1.0.0/valet.config.json dist/valet/api/valet_1.0.0/valet.config.json
cp -f src/pitboss/api/apiconfig.json dist/pitboss/api/apiconfig.json
cp -f src/pitboss/api/pitboss_1.0.0/pitboss.config.json dist/pitboss/api/pitboss_1.0.0/pitboss.config.json
cp -f src/screech/api/apiconfig.json dist/screech/api/apiconfig.json
cp -f src/screech/api/screech_1.0.0/screech.config.json dist/screech/api/screech_1.0.0/screech.config.json
cp -f src/latchkey/api/apiconfig.json dist/latchkey/api/apiconfig.json
cp -f src/latchkey/api/latchkey_1.0.0/latchkey.config.json dist/latchkey/api/latchkey_1.0.0/latchkey.config.json
cp -f src/latchkey/api/accntmgmt_1.0.0/accntmgmt.config.json dist/latchkey/api/accntmgmt_1.0.0/accntmgmt.config.json
cp -f src/latchkey/api/accntmgmt_1.0.0/account_blacklist/blacklist.json dist/latchkey/api/accntmgmt_1.0.0/account_blacklist/blacklist.json
echo 'Building sources...'
tsc
echo 'Complete.'
