#! /usr/bin/env bash
echo 'Removing targets from dist directory...'
find ~/Dropbox/Tech/Projects/Pancake/dist -type f -name '*.js' -exec rm "{}" +
find ~/Dropbox/Tech/Projects/Pancake/dist -type f -name '*.map' -exec rm "{}" +
echo 'Complete.'
